name: Test coverage

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7
      - run: cd app
      - run: make lint
      - run: make test
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v9.0.0
        env:
          coverage-token: {{secrets.QLTY_COVERAGE_TOKEN}}
          JACOCO_SOURCE_PATH: ${{github.workspace}}/app/src/main/java
        with:
          coverageCommand: make report
          coverageLocations: ${{github.workspace}}/app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
